//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thietbiphatsang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class doantn230Entities : DbContext
    {
        public doantn230Entities()
            : base("name=doantn230Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_AnhThietBi> tb_AnhThietBi { get; set; }
        public virtual DbSet<tb_BaiViet> tb_BaiViet { get; set; }
        public virtual DbSet<tb_ChiTietKM> tb_ChiTietKM { get; set; }
        public virtual DbSet<tb_DonDatHang> tb_DonDatHang { get; set; }
        public virtual DbSet<tb_HoSoCaNhan> tb_HoSoCaNhan { get; set; }
        public virtual DbSet<tb_KhuyenMai> tb_KhuyenMai { get; set; }
        public virtual DbSet<tb_NSX> tb_NSX { get; set; }
        public virtual DbSet<tb_TaiKhoan> tb_TaiKhoan { get; set; }
        public virtual DbSet<tb_ThietBi> tb_ThietBi { get; set; }
        public virtual DbSet<tbLoaiThietBi> tbLoaiThietBi { get; set; }
        public virtual DbSet<tb_ChiTietHD> tb_ChiTietHD { get; set; }
    }
}
