//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thietbiphatsang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietKM
    {
        public int id { get; set; }
        public string strMaDotKM { get; set; }
        public string strMaThietBi { get; set; }
        public Nullable<double> floatTiLeGiam { get; set; }
    
        public virtual tb_KhuyenMai tb_KhuyenMai { get; set; }
        public virtual tb_ThietBi tb_ThietBi { get; set; }
    }
}
