//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thietbiphatsang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DonDatHang()
        {
            this.tb_ChiTietHD = new HashSet<tb_ChiTietHD>();
        }
    
        public string strMaDon { get; set; }
        public string strMaKhachHang { get; set; }
        public string strDiaChiNhan { get; set; }
        public Nullable<int> intTrangThai { get; set; }
        public Nullable<System.DateTime> dateTaoLuc { get; set; }
        public Nullable<double> floatTongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietHD> tb_ChiTietHD { get; set; }
        public virtual tb_TaiKhoan tb_TaiKhoan { get; set; }
    }
}
