//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thietbiphatsang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_TaiKhoan()
        {
            this.tb_DonDatHang = new HashSet<tb_DonDatHang>();
        }
    
        public string strID { get; set; }
        public string strPassword { get; set; }
        public Nullable<bool> boolQuyenSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DonDatHang> tb_DonDatHang { get; set; }
        public virtual tb_HoSoCaNhan tb_HoSoCaNhan { get; set; }
    }
}
