//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thietbiphatsang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ThietBi()
        {
            this.tb_AnhThietBi = new HashSet<tb_AnhThietBi>();
            this.tb_BaiViet = new HashSet<tb_BaiViet>();
            this.tb_ChiTietKM = new HashSet<tb_ChiTietKM>();
        }
    
        public string strMaThietBi { get; set; }
        public string strTenThietBi { get; set; }
        public string strMaNSX { get; set; }
        public Nullable<int> intSoLuongTon { get; set; }
        public string strMaLoai { get; set; }
        public Nullable<int> intDienApBD { get; set; }
        public Nullable<int> intCongSuatBD { get; set; }
        public Nullable<int> intDienApKT { get; set; }
        public Nullable<int> intCongSuatKT { get; set; }
        public Nullable<double> floatGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AnhThietBi> tb_AnhThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BaiViet> tb_BaiViet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietKM> tb_ChiTietKM { get; set; }
        public virtual tb_NSX tb_NSX { get; set; }
        public virtual tb_ChiTietHD tb_ChiTietHD { get; set; }
        public virtual tbLoaiThietBi tbLoaiThietBi { get; set; }
    }
}
